CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	department varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	image_name varchar(255) NULL,
	job_title varchar(255) NOT NULL,
	login varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone varchar(255) NOT NULL,
	"role" varchar(255) NULL,
	user_name varchar(255) NOT NULL,
	user_surname varchar(255) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone),
	CONSTRAINT ukow0gan20590jrb00upg3va2fn UNIQUE (login),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])))
);